    var searchMass = [
      {
        name: "New1",
        fullname: "New1",
        searchname:  "New1",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      },
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      },
            {
        name: "New1",
        fullname: "New1",
        searchname:  "New1",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      },
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      },
            {
        name: "New1",
        fullname: "New1",
        searchname:  "New1",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      },
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      },
            {
        name: "New1",
        fullname: "New1",
        searchname:  "New1",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      },
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
      ,
      {
        name: "New2",
        fullname: "New2",
        searchname:  "New2",
        ceo: "Сидоров А.В.",
        searchceo: "Сидоров А.В.",
        money: "13249",
        moneyFormat: "млн.руб",
        profit: "1635",
        result: "1217",
        russianFilter: true,
        //childs: childs,
        childs: [],
        //parents
        parent: false,
        level: 1,
        id: "000",
        show: false,
        clicked: "no",
        val10: undefined,
        url: undefined
      }
    ];
